[controlPlane]
  enabled = true
  serviceURL = "https://wso2apim:9443/"
  username = "admin"
  password = "admin"
  environmentLabels = ["Default"]
  skipSSLVerification = true
  internalKeyIssuer = "http://am.wso2.com:443/token"
  [controlPlane.brokerConnectionParameters]
  eventListeningEndpoints = ["amqp://admin:admin@wso2apim:5672?retries='10'&connectdelay='30'"]

[dataPlane]
  enabled = true
  k8ResourceEndpoint = "https://localhost:9443/api/configurator/apis/generate-k8s-resources"