apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-log-conf
  namespace: {{ .Release.Namespace }}
data:
  config.toml: |
    [controlPlane]
      enabled = true
      serviceURL = "https://am-service.apim-deployment.svc.cluster.local:9443/"
      username = "admin"
      password = "admin"
      environmentLabels = ["Default"]
      skipSSLVerification = true
      [controlPlane.brokerConnectionParameters]
      eventListeningEndpoints = ["amqp://admin:admin@am-service.apim-deployment.svc.cluster.local:5672?retries='10'&connectdelay='30'"]
    
    [dataPlane]
      enabled = true
      k8ResourceEndpoint = "https://apk-test-setup-wso2-apk-config-ds-service.apk-integration-test.svc.cluster.local:9443/api/configurator/apis/generate-k8s-resources"
      namespace = "apk-integration-test"
  log_config.toml: |
    # The logging configuration for Adapter

    ## Adapter root Level configurations
      
      logLevel = "INFO" # LogLevels can be "DEBG", "FATL", "ERRO", "WARN", "INFO", "PANC"
      LogFormat = "TEXT" # Values can be "JSON", "TEXT"
      
      [rotation]
      MaxSize = 10    # In MegaBytes (MB)
      MaxBackups = 3
      MaxAge =  2   # In days
      Compress = true
    
    ## Adapter package Level configurations
      
      [[pkg]]
      name = "github.com/wso2/apk/adapter/internal/adapter"
      logLevel = "INFO" # LogLevels can be "DEBG", "FATL", "ERRO", "WARN", "INFO", "PANC"
      
      [[pkg]]
      name = "github.com/wso2/apk/adapter/internal/oasparser"
      logLevel = "INFO"
    
    
    # The logging configuration for Router
      
      [accessLogs]
      enable = false
      format = "[%START_TIME%] '%REQ(:METHOD)% %DYNAMIC_METADATA(envoy.filters.http.ext_authz:originalPath)% %REQ(:PATH)% %PROTOCOL%' %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% '%REQ(X-FORWARDED-FOR)%' '%REQ(USER-AGENT)%' '%REQ(X-REQUEST-ID)%' '%REQ(:AUTHORITY)%' '%UPSTREAM_HOST%'\n"
      
      [wireLogs]
      enable = false
      include = ["Headers", "Body", "Trailers"]
    
    # [[pkg]]
    # name = "github.com/wso2/apk/Adapter/pkg/xds"
    # logLevel = "INFO"
